# Generated by Django 3.1.5 on 2021-01-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'data_prefill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.PROTECT, to='core.role'),
            preserve_default=False,
        ),
    ]
