# Generated by Django 3.1.5 on 2021-01-16 11:39

from django.db import migrations


payment_status = ["unassigned", "assigned", "failed", "successful"]
roles = ["user", "artist"]


def forward(apps, _schema_editor):
    # payment
    PaymentStatus = apps.get_model('core', 'PaymentStatus')
    for status in payment_status:
        p = PaymentStatus.objects.get_or_create(status=status)
        print("created", p)
        
    # role
    Role = apps.get_model('core', 'Role')
    for role in roles:
        r = Role.objects.get_or_create(role=role)
        print("created", r)
    
    


def backward(apps, _schema_editor):
    
    # payment
    PaymentStatus = apps.get_model('core', 'PaymentStatus')
    for status in payment_status:
        p = PaymentStatus.objects.get(status=status)
        print("deleted", p)
        p.delete()

    # role
    Role = apps.get_model('core', 'Role')
    for role in roles:
        r = Role.objects.get(role=role)
        print("deleted", r)
        r.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            forward,
            backward
        )
    ]

